pages:
  - name: ホーム - 未来
    path: /2024-03-29
  - name: ホーム - 現在
    path: /
  - name: ホーム - 過去
    path: /2024-03-11
  - name: 出走表
    path: /races/39b86d78-1395-437b-a2e7-7de7fef8c072/race-card
  - name: オッズ - 締め切り前
    path: /races/3f1e578f-241e-4dbd-9096-517dc40f4f4a/odds
  - name: オッズ - 締め切り後
    path: /races/39b86d78-1395-437b-a2e7-7de7fef8c072/odds
  - name: 結果
    path: /races/e5bcc82c-c340-4463-b604-7942efb7fbca/result
viewports:
  - name: Pixel 5
    width: 393
    height: 851
  - name: Kindle Fire HDX
    width: 800
    height: 1280
  - name: Desktop
    width: 1280
    height: 720
